from .heuristic_bots.heuristic_trump_random_play import HeuristicTrumpRandomPlay
from .heuristic_bots.full_heuristic_v1 import FullHeuristicEgocentric
from .heuristic_bots.full_heuristic_v2 import FullHeuristicTableView
from .mcts_bots.heuristic_trump_mcts_play import HeuristicTrumpMCTSPlay
